### ISSUE TITLE
Adjustment of Capability in upload.php to Use Local Capability

### ISSUE THREAD

**Issue by eduardokraus** [catalyst/moodle-tool_smsimport#10]
In the upload.php file, the 'moodle/site:config' capability is being called, when it should actually

![Captura de Tela 2024-11-23 às 15 49 40](https://github.com/user-attachments/assets/8190219e-20eb-4826-ab64-28a582f08163)

**Comment by danmarsden** [comment]
closing as won't fix - this is a site admin tool and fine to use the config capability check like this - happy for someone to submit a patch to improve this, but it's not something we'll prioritise on our end.
