### ISSUE TITLE
 Using html_writer::start_tag is Deprecated – Switch to Mustache for Rendering HTML

### ISSUE THREAD

**Issue by eduardokraus** [catalyst/moodle-tool_smsimport#11]
The use of the `html_writer::start_tag` function is deprecated and no longer recommended in newer versions of Moodle. Instead, it is ideal to use the Mustache template system to render HTML in a more efficient and modern way. Mustache provides a more flexible and cleaner method for inserting dynamic content into pages, ensuring greater consistency and compatibility with future platform updates.

![Captura de Tela 2024-11-23 às 15 51 03](https://github.com/user-attachments/assets/6137a972-9e18-4969-b6b5-c8014112fd83)

**Comment by danmarsden** [comment]
html_writer is not officially deprecated:
https://github.com/moodle/moodle/blob/main/lib/classes/output/html_writer.php

yes - it might be nice to use mustache templates, but using html_writer isn't an issue at the moment so closing this as won't fix.
