### ISSUE TITLE
moodle_exception Class Not Found in upload.php (Line 39)

### ISSUE THREAD

**Issue by eduardokraus** [catalyst/moodle-tool_smsimport#2]
In the upload.php file, at line 39, an error occurs indicating that the moodle_exception class was not found.

![Captura de Tela 2024-11-23 às 15 24 16](https://github.com/user-attachments/assets/75049654-418a-496e-a627-11532e3b967d)

**Comment by danmarsden** [comment]
you will see this in moodle core functions too - not really an issue with the plugin - closing as wont' fix, but feel free to send a PR if you think there's something that can be improved here.
