### ISSUE TITLE
Organizing Imports in Code

### ISSUE THREAD

**Issue by eduardokraus** [catalyst/moodle-tool_smsimport#8]
It would be ideal to have a more organized structure, with all imports made consistently. This not only improves code readability but also makes the project easier to maintain and scale.

![Captura de Tela 2024-11-23 às 15 42 38](https://github.com/user-attachments/assets/d4a0ae77-a61b-487d-adc5-0b2d8afff848)

**Comment by danmarsden** [comment]
thanks for the feedback - this isn't something we'll change at this stage - Moodle is slowly updating those libs in core so they they auto-load and hopefully in future we'll just be able to delete them and migrate to the new classes.
